apiVersion: v1
kind: Service
metadata:
  labels:
    app: db_deployment
  name: db_service
spec:
  ports:
  - nodePort: 30011
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db_deployment
  type: NodePort
